source 'git@git.oschina.net:leeszi/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'SchemeNavigator_Example' do
  pod 'SchemeNavigator', :path => '../'
  pod 'TOWebViewController'
  target 'SchemeNavigator_Tests' do
    inherit! :search_paths

    
  end
end
